name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - run: npm install
      - run: npm test
      
      - run: npm run coverage
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: coverage